### ISSUE TITLE
Cancel valueEventFlow().collect within viewModelScope.launch {}

### ISSUE THREAD

**Issue by Bigboer** [KaustubhPatange/firebase-realtime-extensions#1]
I am using your library with android.lifecycle and not CoroutineScope(Dispatchers.Main + job).launch
How do i cancel or stop collecting?

Example:
`viewModelScope.launch {
database.child("ref").valueEventFlow().collect {
// Do stuff
}
}`

**Comment by Bigboer** [comment]
Ahh i answered it for myself.

```
job = viewModelScope.launch {

}

job.cancel()
```

**Comment by KaustubhPatange** [comment]
In Readme, there is `CoroutineScope(... + job)`, here in place of ... use `lifecycleScope.coroutineContext`.

**Comment by Bigboer** [comment]
Thanks that works as well!
